image: python:3.9

cache:
  paths:
    - ~/.cache/pip
    - ~/.platformio/.cache

stages:
 - build_release
 #- build
 #- release

before_script:
  - "pip install -U platformio"
  
#build_debug:
#  stage: build_debug
#  variables:
#    GIT_STRATEGY: clone
#  script: 
#    - "pio run -e FuelStationHardware_DEBUG -d $CI_PROJECT_DIR"
#    - pwd
#    - ls -al
#    - mkdir -p $CI_PROJECT_DIR/artifacts
#    - ls .pio/build/FuelStationHardware_DEBUG
#    - cp .pio/build/FuelStationHardware_DEBUG/GA_FUEL_TERMINAL*.elf $CI_PROJECT_DIR/artifacts
#    - cp .pio/build/FuelStationHardware_DEBUG/GA_FUEL_TERMINAL*.bin $CI_PROJECT_DIR/artifacts
#    #- cp GA_FUEL_TERMINAL* artifacts/
#    - ls -al $CI_PROJECT_DIR/artifacts/
#  artifacts:
#    paths:
#    - artifacts/GA_FUEL_TERMINAL*.bin
#    #- artifacts/GA_FUEL_TERMINAL*.elf

build_release:
  stage: build_release
  only:
    - tags
  variables:
    GIT_STRATEGY: clone
  script: 
    - "pio run -e FuelStationHardware_RELEASE -d $CI_PROJECT_DIR"
    - "pio run -e FuelStationHardware_RELEASE --target buildfs -d $CI_PROJECT_DIR"
    - pwd
    - ls -al
    - mkdir -p $CI_PROJECT_DIR/artifacts
    - ls .pio/build/FuelStationHardware_RELEASE
    - cp .pio/build/FuelStationHardware_RELEASE/GA_FUEL_TERMINAL*.elf $CI_PROJECT_DIR/artifacts
    - cp .pio/build/FuelStationHardware_RELEASE/GA_FUEL_TERMINAL*.bin $CI_PROJECT_DIR/artifacts
    - cp .pio/build/FuelStationHardware_RELEASE/littlefs.bin $CI_PROJECT_DIR/artifacts
    - ls -al $CI_PROJECT_DIR/artifacts/
  artifacts:
    paths:
    - artifacts/GA_FUEL_TERMINAL*.bin
    - artifacts/GA_FUEL_TERMINAL*.elf
    - artifacts/littlefs.bin

#release:
#  stage: release
#  script: "pio run -e FuelStationHardware_RELEASE"
#  only: 
#    - tags
