; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32@^6.4.0
platform_packages = platformio/framework-arduinoespressif32@^3.20014.231204
framework = arduino
lib_deps = 
	computer991/Arduino_MFRC522v2@^2.0.1
	Wire
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	intrbiz/Crypto@^1.0.0
	#jandrassy/EthernetENC @ ^2.0.3
	esphome/ESPAsyncWebServer-esphome @ ^3.0.0
	bblanchon/ArduinoJson @ ^6.21.2
	densaugeo/base64 @ ^1.4.0
	ayushsharma82/AsyncElegantOTA @ ^2.2.7
	esphome/AsyncTCP-esphome@2.0.1

board_build.filesystem = littlefs
monitor_speed = 115200
extra_scripts = 
    pre:auto_firmware_version.py

[env:FuelStationHardware_OLD]
board = esp32-s3-devkitc-1
debug_tool = esp-builtin


[env:FuelStationHardware_DEBUG]
board = ga_fuel_station
debug_tool = esp-builtin
build_flags = -DCORE_DEBUG_LEVEL=5 -DBACKLIGHT_DIM


[env:FuelStationHardware_RELEASE]
board = ga_fuel_station
debug_tool = esp-builtin
build_flags = -DCORE_DEBUG_LEVEL=5 -DBACKLIGHT_DIM

