; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
lib_deps = 
	computer991/Arduino_MFRC522v2@^2.0.1
	Wire
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	intrbiz/Crypto@^1.0.0
	jandrassy/EthernetENC @ ^2.0.3
	esphome/ESPAsyncWebServer-esphome @ ^3.0.0
	bblanchon/ArduinoJson @ ^6.21.2
	densaugeo/base64 @ ^1.4.0
	ayushsharma82/AsyncElegantOTA @ ^2.2.7

board_build.filesystem = littlefs

monitor_speed = 115200

[env:FuelStationHardware_OLD]
platform = espressif32
board = esp32-s3-devkitc-1
debug_tool = esp-builtin


[env:FuelStationHardware_DEBUG]
#build_type = debug
platform = espressif32
board = ga_fuel_station
debug_tool = esp-builtin
build_flags = -DCORE_DEBUG_LEVEL=5

[env:FuelStationHardware_RELEASE]
platform = espressif32
board = ga_fuel_station
debug_tool = esp-builtin
build_flags = -DCORE_DEBUG_LEVEL=2

