void init_FS();
int vprintf_into_fs(const char* szFormat, ...);
void loadConfiguration(const char *filename, t_Config &config);
void printConfig(t_Config &config);
int storeRefueling(JsonDocument &);
int numberOfRefuelingFiles();
int getNextRefuelingFileName(char *);
int readRefuelingFile(const char * path, JsonDocument &);
int deleteRefuelingFile(char *fileName);
String listFiles(bool ishtml);