void lcd_init();
void lcd_WaitForTransponder();
void lcd_WelcomeMessage();
void lcd_ConnectingWIFI();
void lcd_ShowIP(char *);
void lcd_UpdateStatus(t_refueling, t_terminalStatus);
void lcd_ShowAircraft(t_refueling);
void lcd_UpdateFuelCount(t_refueling);
void lcd_ShowCount();
void lcd_SendData();
void lcd_SendDataResult(int);
void lcd_OfflineMessage();
void lcd_Backlight(int);