#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_SPECIAL "dev"


#define STRINGIFY0(s) # s
#define STRINGIFY(s) STRINGIFY0(s)

#define VERSION "V "STRINGIFY(VERSION_MAJOR)"."STRINGIFY(VERSION_MINOR)"."VERSION_SPECIAL